# Workflow name
name: FrontEndWorkflow

# Triggers for the workflow
on:
  # Automatic trigger on pull request events targeting the main branch
  pull_request:
    branches:
      - main

# Jobs defined in the workflow
jobs:
  build:
    # The operating system for the runner
    runs-on: ubuntu-latest

    # Steps in the job
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: latest

    - name: Print a message
      run: echo "Hello, world!"